twitter:
    name: 'bwong337'
    consumer_key: 'jYsr58JmmXDAo9INZWmJDzt1F'
    consumer_secret: 'HHmWD4d6cMwBfe2RwbyeFL2nETxRuc5t9ZriVxe0l3udJHFvBq'
    oauth_token: '562620090-Y9TN9AMa6T9MXFuGmvQ0m0W1GzFgqrlyFYTpuOki'
    oauth_token_secret:'f8Vl2jHfe7zXwLPiUvvy4fn9P7h0VL5D3uO3u6OGfa9aZ'